## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [1]:
import os
import numpy as np
import pandas as pd

In [8]:
# 設定 data_path
dir_data = r'C:\Users\user\Documents\GitHub\2nd-ML100Days'

In [9]:
f_app = os.path.join(dir_data, 'application_test.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: C:\Users\user\Documents\GitHub\2nd-ML100Days\application_test.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [31]:
app_train.head(10)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5,100042,Cash loans,F,Y,Y,0,270000.0,959688.0,34600.5,810000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
6,100057,Cash loans,M,Y,Y,2,180000.0,499221.0,22117.5,373500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
7,100065,Cash loans,M,N,Y,0,166500.0,180000.0,14220.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
8,100066,Cash loans,F,N,Y,0,315000.0,364896.0,28957.5,315000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
9,100067,Cash loans,F,Y,Y,1,162000.0,45000.0,5337.0,45000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0

#### 列出所有欄位

In [39]:
app_train.head(121)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5,100042,Cash loans,F,Y,Y,0,270000.0,959688.0,34600.5,810000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
6,100057,Cash loans,M,Y,Y,2,180000.0,499221.0,22117.5,373500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
7,100065,Cash loans,M,N,Y,0,166500.0,180000.0,14220.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
8,100066,Cash loans,F,N,Y,0,315000.0,364896.0,28957.5,315000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
9,100067,Cash loans,F,Y,Y,1,162000.0,45000.0,5337.0,45000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
10,100074,Cash loans,F,N,Y,0,67500.0,675000.0,25447.5,675000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
11,100090,Cash loans,F,N,Y,0,135000.0,261621.0,16848.0,216000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
12,100091,Cash loans,F,N,Y,0,247500.0,296280.0,23539.5,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
13,100092,Cash loans,F,Y,Y,0,90000.0,360000.0,18535.5,360000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
14,100106,Revolving loans,M,N,Y,0,180000.0,157500.0,7875.0,157500.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
15,100107,Cash loans,M,Y,Y,0,180000.0,296280.0,21690.0,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
16,100109,Cash loans,F,Y,Y,0,202500.0,407520.0,26041.5,360000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
17,100117,Cash loans,M,Y,Y,0,90000.0,499221.0,22117.5,373500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
18,100128,Cash loans,F,Y,Y,1,225000.0,431280.0,23526.0,360000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,3.0,4.0
19,100141,Cash loans,F,Y,Y,0,175500.0,478498.5,46741.5,454500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
20,100150,Cash loans,F,N,Y,0,99000.0,225000.0,19242.0,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
21,100168,Cash loans,F,N,Y,0,157500.0,266652.0,16443.0,202500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
22,100169,Cash loans,F,N,Y,0,135000.0,540000.0,27702.0,540000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
23,100170,Cash loans,M,N,Y,1,337500.0,1313212.5,42493.5,1012500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
24,100171,Cash loans,M,Y,Y,0,157500.0,539100.0,29245.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
25,100172,Cash loans,F,N,Y,0,76500.0,225000.0,12334.5,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
26,100184,Cash loans,F,N,Y,0,112500.0,256032.0,10759.5,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
27,100187,Cash loans,F,N,Y,0,225000.0,501363.0,25726.5,418500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100212,Cash loans,F,Y,N,0,90000.0,450000.0,23107.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
29,100222,Cash loans,F,Y,Y,0,360000.0,945000.0,34074.0,945000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,100744,Cash loans,F,N,Y,2,144000.0,225000.0,17905.5,225000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
92,100745,Cash loans,F,N,Y,0,135000.0,900000.0,29034.0,900000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
93,100747,Cash loans,M,Y,Y,0,495000.0,691551.0,54769.5,625500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,4.0,0.0
94,100751,Cash loans,F,N,N,1,67500.0,450000.0,14517.0,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
95,100752,Cash loans,M,Y,Y,0,135000.0,675000.0,27229.5,675000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
96,100753,Cash loans,F,Y,Y,0,180000.0,156384.0,18688.5,135000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
97,100754,Cash loans,M,Y,Y,0,135000.0,364500.0,13221.0,364500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
98,100760,Cash loans,M,N,Y,0,90000.0,224149.5,22297.5,193500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
99,100762,Cash loans,F,N,N,0,180000.0,225000.0,20637.0,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100,100763,Cash loans,F,Y,Y,0,157500.0,571486.5,24340.5,454500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
101,100765,Cash loans,F,Y,N,2,112500.0,136287.0,8847.0,103500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
102,100770,Cash loans,M,Y,N,0,202500.0,697500.0,33687.0,697500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
103,100772,Cash loans,M,Y,N,0,315000.0,1096020.0,56092.5,900000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
104,100777,Cash loans,M,Y,Y,1,360000.0,1024740.0,52452.0,900000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
105,100791,Cash loans,F,Y,N,1,135000.0,276277.5,17784.0,238500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
106,100792,Cash loans,F,N,Y,1,90000.0,276277.5,17784.0,238500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
107,100797,Cash loans,F,N,Y,0,180000.0,1055655.0,38047.5,891000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
108,100823,Cash loans,M,Y,Y,0,202500.0,585000.0,29997.0,585000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
109,100826,Cash loans,F,N,N,1,202500.0,450000.0,14517.0,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
110,100830,Cash loans,F,N,N,0,112500.0,625536.0,31936.5,540000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
111,100836,Cash loans,M,N,N,2,67500.0,234576.0,20263.5,202500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
112,100872,Cash loans,M,Y,Y,1,135000.0,1024740.0,49428.0,900000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
113,100910,Cash loans,F,Y,N,0,202500.0,67500.0,7218.0,67500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
114,100913,Cash loans,F,N,Y,0,157500.0,720000.0,30505.5,720000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
115,100918,Cash loans,M,Y,N,0,180000.0,118512.0,7573.5,90000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
116,100931,Cash loans,M,Y,Y,0,189000.0,260640.0,25906.5,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
117,100952,Cash loans,M,Y,Y,1,112500.0,675000.0,34596.0,675000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,3.0,1.0
118,100953,Cash loans,M,N,N,0,225000.0,573408.0,29407.5,495000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
119,100965,Cash loans,F,Y,N,0,90000.0,202500.0,13068.0,202500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
120,100970,Cash loans,F,N,Y,0,112500.0,599778.0,27792.0,477000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0

#### 截取部分資料

In [34]:
app_train.head(5)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子